-- Add up migration script here
CREATE TABLE IF NOT EXISTS ROLES (
    ROLE_ID INTEGER PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFILES (
    PROFILE_ID INTEGER PRIMARY KEY NOT NULL,
    PHONE_NO CHAR(10) UNIQUE,
    LOCATION VARCHAR(20),
    LANGUAGES VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INTEGER PRIMARY KEY NOT NULL,
    USER_NAME VARCHAR(20) UNIQUE NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL, 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DOB CHAR(10) NOT NULL,
    PROFILE_ID INTEGER,
    FOREIGN KEY (PROFILE_ID) REFERENCES PROFILES(PROFILE_ID)
);