CREATE TABLE IF NOT EXISTS ROLES (
    role_id INT PRIMARY KEY AUTO_INCREMENT,
    role_name VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFILES (
    profile_id INT PRIMARY KEY AUTO_INCREMENT,
    phone_no CHAR(10) UNIQUE,
    location VARCHAR(20),
    languages VARCHAR(200),
    about VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS USERS (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    role_id INT NOT NULL,
    FOREIGN KEY (role_id) REFERENCES ROLES(role_id),
    username VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(30) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dob CHAR(10) NOT NULL,
    profile_id INT UNIQUE,
    FOREIGN KEY (profile_id) REFERENCES PROFILES(profile_id)
);

/*
USER = 1
MODERATOR = 2
ADMIN = 3
 */
INSERT INTO ROLES VALUES(1, "USER");
INSERT INTO ROLES VALUES(2, "ADMIN");
INSERT INTO ROLES VALUES(3, "MODERATOR");