/* DROP TABLES REACTIONS, PROFILES, RETWEETS, ROLES, TWEETS, USERS, FOLLOWING; */

CREATE TABLE IF NOT EXISTS ROLES (
    role_id INT PRIMARY KEY AUTO_INCREMENT,
    role_name VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    role_id INT NOT NULL,
    FOREIGN KEY (role_id) REFERENCES ROLES(role_id),
    username VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dob CHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFILES (
    username VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (username) REFERENCES USERS(username),
    phone_no CHAR(10) UNIQUE,
    location VARCHAR(20),
    languages VARCHAR(200),
    about VARCHAR(500),
    profilepicurl VARCHAR(500),
    bannerurl VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS TWEETS (
    tweet_id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL,
    FOREIGN KEY (username) REFERENCES USERS(username),
    parent_id INT,
    FOREIGN KEY (parent_id) REFERENCES TWEETS(tweet_id),
    content VARCHAR(300) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    likes INT DEFAULT 0 NOT NULL,
    retweets INT DEFAULT 0 NOT NULL,
    quotes INT DEFAULT 0 NOT NULL,
    views INT DEFAULT 0 NOT NULL,
    replies INT DEFAULT 0 NOT NULL,
    quote_id INT,
    FOREIGN KEY (quote_id) REFERENCES TWEETS(tweet_id)
);

CREATE TABLE IF NOT EXISTS REACTIONS (
    username VARCHAR(20) NOT NULL,
    FOREIGN KEY (username) REFERENCES USERS(username),
    tweet_id INT NOT NULL,
    FOREIGN KEY (tweet_id) REFERENCES TWEETS(tweet_id),
    PRIMARY KEY(username, tweet_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reaction_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS RETWEETS (
    username VARCHAR(20) NOT NULL,
    FOREIGN KEY (username) REFERENCES USERS(username),
    tweet_id INT NOT NULL,
    FOREIGN KEY (tweet_id) REFERENCES TWEETS(tweet_id),
    PRIMARY KEY(username, tweet_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FOLLOWING (
    username VARCHAR(20) NOT NULL,
    FOREIGN KEY (username) REFERENCES USERS(username),
    following VARCHAR(20) NOT NULL,
    FOREIGN KEY (following) REFERENCES USERS(username),
    PRIMARY KEY (username, following),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ROLES VALUES(1, "USER");
INSERT INTO ROLES VALUES(2, "ADMIN");
INSERT INTO ROLES VALUES(3, "MODERATOR");