version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysqlDB
    env_file:
      - ./.env
    ports:
      - "6500:3306"
    volumes:
      - mysqlDB:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: redis-sessiondb
    env_file:
      - ./.env
    ports:
      - 6379:6379
    volumes:
      - redis-sessiondb:/data
volumes:
  mysqlDB:
  redis-sessiondb:
